// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd7zfw-LfGa8jkQMea0QaygW2c2NpeLz8',
    appId: '1:602558771832:web:765d97cdc5dbddb2d3f38d',
    messagingSenderId: '602558771832',
    projectId: 'flutterprojectstest-5ecce',
    authDomain: 'flutterprojectstest-5ecce.firebaseapp.com',
    storageBucket: 'flutterprojectstest-5ecce.appspot.com',
    measurementId: 'G-4KWCD9JZPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCScMYqXY4mefT_rulNiMOvZtmsBG_fXEo',
    appId: '1:602558771832:android:9272180241cf456bd3f38d',
    messagingSenderId: '602558771832',
    projectId: 'flutterprojectstest-5ecce',
    storageBucket: 'flutterprojectstest-5ecce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSK-P_FGXaUbObUiX9tjOiwdL05zCNYao',
    appId: '1:602558771832:ios:70fc1f853d542bddd3f38d',
    messagingSenderId: '602558771832',
    projectId: 'flutterprojectstest-5ecce',
    storageBucket: 'flutterprojectstest-5ecce.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSK-P_FGXaUbObUiX9tjOiwdL05zCNYao',
    appId: '1:602558771832:ios:4735a7ba501258cdd3f38d',
    messagingSenderId: '602558771832',
    projectId: 'flutterprojectstest-5ecce',
    storageBucket: 'flutterprojectstest-5ecce.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
